# Generated by Django 3.2 on 2021-05-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Key',
            field=models.CharField(blank=True, choices=[('t', 'Title'), ('r', 'Rise'), ('z', 'Zero')], default='r', max_length=1),
        ),
    ]
