# Generated by Django 3.2 on 2021-05-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Key',
        ),
        migrations.AddField(
            model_name='book',
            name='word',
            field=models.CharField(choices=[('t', 'The')], default='t', max_length=1),
        ),
    ]
